name: FromTest

on:
  schedule:
    - cron: '*/5 * * * *'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
        
      - name: Run a new script
        run: |
          current_version="v0.0"
          new_version=$(git -c 'versionsort.suffix=-' \
          ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/swig/swig/ '*.*.*' \
          | tail --lines=1 \
          | cut --delimiter='/' --fields=3)
          if [ $new_version == $current_version ]; then
            echo "Up to date with $current_version"
          else
            echo "Update to $new_version"
            #gh pr create --title "New version $new_version of swig has been released" --body ""
            #gh pr create --project "test"
          fi


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add report file
          title: '[Example] Add report file'
          body: >
            This PR is auto-generated by 
            [create-pull-request](https://github.com/rbSparky).
          labels: report, automated pr
